# Generated by Django 4.1.7 on 2023-02-18 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auther',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('host', models.CharField(max_length=200)),
                ('displayName', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('github', models.CharField(max_length=200)),
                ('profileImage', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('comment', models.CharField(max_length=200)),
                ('contentType', models.CharField(max_length=200)),
                ('published', models.DateTimeField()),
                ('auther', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_distribution.auther')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('contentType', models.CharField(max_length=200)),
                ('categories', models.CharField(max_length=200)),
                ('count', models.IntegerField()),
                ('comments', models.CharField(max_length=200)),
                ('published', models.DateTimeField()),
                ('visibility', models.CharField(max_length=200)),
                ('unlisted', models.BooleanField()),
                ('auther', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_distribution.auther')),
                ('commentSrc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_distribution.comment')),
            ],
        ),
    ]
