# Generated by Django 4.1.7 on 2023-02-27 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_distribution', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followers',
            name='type',
            field=models.CharField(default='Follower', max_length=200),
        ),
        migrations.AlterField(
            model_name='friendrequest',
            name='requestCategory',
            field=models.CharField(choices=[('none', 'None'), ('friend', 'Friend'), ('follow', 'Follow'), ('accept', 'Accept')], default='none', max_length=200),
        ),
    ]
