# Generated by Django 4.1.7 on 2023-03-16 00:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('social_distribution', '0002_alter_author_host_alter_author_url_alter_post_friend'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='contentType',
            field=models.CharField(default='text/plain', max_length=200),
        ),
        migrations.AlterField(
            model_name='like',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='social_distribution.comment'),
        ),
        migrations.AlterField(
            model_name='like',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='social_distribution.post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='origin',
            field=models.CharField(default='http://localhost:8000/service/posts/', max_length=200),
        ),
    ]
