# Generated by Django 4.1.7 on 2023-02-18 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_distribution', '0002_rename_auther_author'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Author',
            new_name='User',
        ),
    ]
