# Generated by Django 4.1.7 on 2023-03-01 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_distribution', '0003_alter_author_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.CharField(default='dd6be0fe059648f7a3eb6b736e6571b6', editable=False, max_length=32, primary_key=True, serialize=False),
        ),
    ]
