# Generated by Django 4.1.7 on 2023-02-23 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_distribution', '0003_rename_auther_comment_author_remove_post_auther_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='password',
            field=models.CharField(default='test', max_length=200),
            preserve_default=False,
        ),
    ]
