# Generated by Django 4.1.7 on 2023-03-01 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_distribution', '0004_alter_author_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.CharField(default='b29c56d92a254d75b6c15696316362c2', editable=False, max_length=32, primary_key=True, serialize=False),
        ),
    ]
