# Generated by Django 4.1.7 on 2023-03-03 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_distribution', '0004_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(default=20, on_delete=django.db.models.deletion.CASCADE, to='social_distribution.post'),
            preserve_default=False,
        ),
    ]
