# Generated by Django 4.1.7 on 2023-02-23 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_distribution', '0004_author_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='username',
            field=models.CharField(default='test', max_length=200),
            preserve_default=False,
        ),
    ]
