# Generated by Django 4.1.7 on 2023-02-19 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_distribution', '0004_post_origin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='auther',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='auther',
            new_name='author',
        ),
    ]
