# Generated by Django 4.1.7 on 2023-03-04 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_distribution', '0005_comment_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='visibility',
            field=models.CharField(default='PUBLIC', max_length=200),
        ),
        migrations.CreateModel(
            name='Inbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_distribution.author')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_distribution.post')),
            ],
        ),
    ]
