# Generated by Django 4.1.7 on 2023-02-19 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_distribution', '0007_alter_comment_id_alter_post_id_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(default='No description', max_length=2000),
        ),
    ]
