# Generated by Django 4.1.7 on 2023-02-23 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_distribution', '0009_user_friends_friendrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendrequest',
            old_name='senderUser',
            new_name='actor',
        ),
        migrations.RenameField(
            model_name='friendrequest',
            old_name='recieverUser',
            new_name='object',
        ),
        migrations.AddField(
            model_name='friendrequest',
            name='requestCategory',
            field=models.CharField(choices=[('none', 'None'), ('friend', 'Friend'), ('follow', 'Follow')], default='none', max_length=200),
        ),
        migrations.AddField(
            model_name='friendrequest',
            name='summary',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(blank=True, to='social_distribution.user'),
        ),
    ]
