# Generated by Django 4.1.7 on 2023-03-07 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_distribution', '0010_alter_followers_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followers',
            name='items',
            field=models.ManyToManyField(blank=True, to='social_distribution.author'),
        ),
        migrations.CreateModel(
            name='like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_distribution.author')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_distribution.post')),
            ],
        ),
    ]
