# Generated by Django 4.1.7 on 2023-02-23 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_distribution', '0010_rename_senderuser_friendrequest_actor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(blank=True, null=True, to='social_distribution.user'),
        ),
    ]
