# Generated by Django 4.1.7 on 2023-02-23 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_distribution', '0011_alter_user_friends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='friends',
        ),
        migrations.CreateModel(
            name='Followers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='Followers', max_length=200)),
                ('items', models.ManyToManyField(blank=True, null=True, to='social_distribution.user')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='followersList',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='social_distribution.followers'),
        ),
    ]
