# Generated by Django 4.1.7 on 2023-02-23 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_distribution', '0012_remove_user_friends_followers_user_followerslist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='followersList',
        ),
        migrations.AddField(
            model_name='followers',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='social_distribution.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='displayName',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
