# Generated by Django 4.1.7 on 2023-03-07 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_distribution', '0012_alter_author_id_alter_comment_id_alter_followers_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='github',
            field=models.CharField(default='No github', max_length=200),
        ),
        migrations.AlterField(
            model_name='author',
            name='profileImage',
            field=models.CharField(default='No profileImage', max_length=200),
        ),
    ]
