# Generated by Django 4.1.7 on 2023-03-07 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_distribution', '0013_alter_author_github_alter_author_profileimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='type',
            field=models.CharField(default='author', max_length=200),
        ),
        migrations.AddField(
            model_name='comment',
            name='type',
            field=models.CharField(default='comment', max_length=200),
        ),
        migrations.AddField(
            model_name='inbox',
            name='type',
            field=models.CharField(default='inbox', max_length=200),
        ),
        migrations.AddField(
            model_name='like',
            name='type',
            field=models.CharField(default='like', max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='type',
            field=models.CharField(default='post', max_length=200),
        ),
    ]
