# Generated by Django 4.1.7 on 2023-03-07 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_distribution', '0014_author_type_comment_type_inbox_type_like_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inboxitem',
            name='comments',
            field=models.ManyToManyField(blank=True, to='social_distribution.comment'),
        ),
        migrations.AddField(
            model_name='inboxitem',
            name='likes',
            field=models.ManyToManyField(blank=True, to='social_distribution.like'),
        ),
    ]
