# Generated by Django 4.1.7 on 2023-03-07 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_distribution', '0015_inboxitem_comments_inboxitem_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='type',
            field=models.CharField(default='request', max_length=200),
        ),
    ]
