# Generated by Django 4.1.7 on 2023-03-08 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_distribution', '0017_remove_friendrequest_actor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='followers',
        ),
        migrations.AddField(
            model_name='author',
            name='followering',
            field=models.ManyToManyField(blank=True, to='social_distribution.author'),
        ),
    ]
