# Generated by Django 4.1.7 on 2023-03-08 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_distribution', '0020_remove_author_following_follow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='profileImage',
            field=models.CharField(default='https://i.imgur.com/k7XVwpB.jpeg', max_length=200),
        ),
    ]
