# Generated by Django 4.1.7 on 2023-04-01 09:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('type', models.CharField(default='author', max_length=200)),
                ('host', models.CharField(default='https://t20-social-distribution.herokuapp.com', max_length=200)),
                ('displayName', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200)),
                ('url', models.CharField(default='https://t20-social-distribution.herokuapp.com/service/authors/', max_length=200)),
                ('github', models.CharField(default='No github', max_length=200)),
                ('profileImage', models.CharField(default='https://i.imgur.com/k7XVwpB.jpeg', max_length=200)),
                ('password', models.CharField(default='No password', max_length=200)),
                ('hidden', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('type', models.CharField(default='comment', max_length=200)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.CharField(max_length=200)),
                ('contentType', models.CharField(default='text/plain', max_length=200)),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_distribution.author')),
            ],
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('type', models.CharField(default='follow', max_length=200)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('summary', models.CharField(default='No summary', max_length=200)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='social_distribution.author')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to='social_distribution.author')),
            ],
        ),
        migrations.CreateModel(
            name='PostURL',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=200)),
                ('source', models.CharField(default=None, max_length=200)),
                ('type', models.CharField(default='postURL', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('type', models.CharField(default='post', max_length=200)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='No title', max_length=200)),
                ('source', models.CharField(default='No source', max_length=200)),
                ('origin', models.CharField(default='no origin', max_length=200)),
                ('description', models.CharField(default='No description', max_length=2000)),
                ('contentType', models.CharField(default='text/plain', max_length=200)),
                ('image_data', models.CharField(blank=True, max_length=100000, null=True)),
                ('authorName', models.CharField(default='No authorName', max_length=200)),
                ('categories', models.CharField(default='No categories', max_length=200)),
                ('count', models.IntegerField(default=0)),
                ('comments', models.CharField(default='No comments', max_length=200)),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('visibility', models.CharField(default='PUBLIC', max_length=200)),
                ('unlisted', models.BooleanField(default=False)),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='social_distribution.author')),
                ('commentSrc', models.ManyToManyField(blank=True, related_name='commentSrc', to='social_distribution.comment')),
                ('friend', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='friend', to='social_distribution.author')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('type', models.CharField(default='like', max_length=200)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_distribution.author')),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='social_distribution.comment')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='social_distribution.post')),
            ],
        ),
        migrations.CreateModel(
            name='Inbox',
            fields=[
                ('type', models.CharField(default='inbox', max_length=200)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_distribution.author')),
                ('comments', models.ManyToManyField(blank=True, to='social_distribution.comment')),
                ('follows', models.ManyToManyField(blank=True, to='social_distribution.follow')),
                ('likes', models.ManyToManyField(blank=True, to='social_distribution.like')),
                ('postURLs', models.ManyToManyField(blank=True, to='social_distribution.posturl')),
                ('posts', models.ManyToManyField(blank=True, to='social_distribution.post')),
            ],
        ),
        migrations.CreateModel(
            name='FollowRequest',
            fields=[
                ('type', models.CharField(default='followRequest', max_length=200)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('summary', models.CharField(default='No summary', max_length=200)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requestAuthor', to='social_distribution.author')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requestFollower', to='social_distribution.author')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_distribution.post'),
        ),
    ]
