# Generated by Django 4.1.7 on 2023-04-01 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_distribution', '0001_initial'),
    ]

    operations = [
    ]
