# Generated by Django 4.1.7 on 2023-04-01 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_distribution', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posturl',
            name='source',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
