# Generated by Django 4.1.7 on 2023-04-03 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_distribution', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='use_markdown',
            field=models.BooleanField(default=False),
        ),
    ]
