# Generated by Django 4.1.7 on 2023-03-29 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_distribution', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='like',
            name='post',
        ),
        migrations.AddField(
            model_name='comment',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='like',
            name='object',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AddField(
            model_name='like',
            name='objectLiked',
            field=models.CharField(choices=[('Comment', 'Comment'), ('Post', 'Post'), ('None', 'None')], default='None', max_length=200),
        ),
        migrations.AddField(
            model_name='like',
            name='summary',
            field=models.CharField(default='No summary', max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='author',
            name='host',
            field=models.CharField(default='https://t20-social-distribution.herokuapp.com', max_length=200),
        ),
        migrations.AlterField(
            model_name='author',
            name='url',
            field=models.CharField(default='https://t20-social-distribution.herokuapp.com/service/authors/', max_length=200),
        ),
        migrations.AlterField(
            model_name='like',
            name='type',
            field=models.CharField(default='Like', max_length=200),
        ),
    ]
