# Generated by Django 4.1.7 on 2023-04-01 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_distribution', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbox',
            name='follows',
            field=models.ManyToManyField(blank=True, to='social_distribution.followrequest'),
        ),
    ]
