# Generated by Django 4.1.7 on 2023-03-30 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_distribution', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='author',
            name='host',
            field=models.CharField(default='https://t20-social-distribution.herokuapp.com', max_length=200),
        ),
        migrations.AlterField(
            model_name='author',
            name='url',
            field=models.CharField(default='https://t20-social-distribution.herokuapp.com/service/authors/', max_length=200),
        ),
    ]
