# Generated by Django 4.1.7 on 2023-04-03 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_distribution', '0002_post_use_markdown'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='use_markdown',
        ),
    ]
