# Generated by Django 4.1.7 on 2023-02-24 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_distribution', '0002_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='authorName',
            field=models.CharField(default='No authorName', max_length=200),
        ),
    ]