# Generated by Django 4.1.7 on 2023-03-31 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_distribution', '0002_post_image_alter_author_host_alter_author_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AddField(
            model_name='post',
            name='image_data',
            field=models.CharField(blank=True, max_length=100000, null=True),
        ),
    ]
