# Generated by Django 4.1.7 on 2023-03-16 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_distribution', '0003_author_hidden_alter_author_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='host',
            field=models.CharField(default='http://127.0.0.1:8000', max_length=200),
        ),
        migrations.AlterField(
            model_name='author',
            name='password',
            field=models.CharField(default='No password', max_length=200),
        ),
        migrations.AlterField(
            model_name='author',
            name='url',
            field=models.CharField(default='http://127.0.0.1:8000/service/authors/', max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='origin',
            field=models.CharField(default='http://127.0.0.1:8000/service/posts/', max_length=200),
        ),
    ]
