# Generated by Django 4.1.7 on 2023-03-22 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_distribution', '0005_alter_author_host_alter_author_url_alter_post_origin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inbox',
            name='items',
        ),
        migrations.AddField(
            model_name='inbox',
            name='comments',
            field=models.ManyToManyField(blank=True, to='social_distribution.comment'),
        ),
        migrations.AddField(
            model_name='inbox',
            name='follows',
            field=models.ManyToManyField(blank=True, to='social_distribution.follow'),
        ),
        migrations.AddField(
            model_name='inbox',
            name='likes',
            field=models.ManyToManyField(blank=True, to='social_distribution.like'),
        ),
        migrations.AddField(
            model_name='inbox',
            name='posts',
            field=models.ManyToManyField(blank=True, to='social_distribution.post'),
        ),
        migrations.DeleteModel(
            name='InboxItem',
        ),
    ]
