# Generated by Django 4.1.7 on 2023-03-04 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_distribution', '0008_alter_inboxitem_posts_alter_inboxitem_requests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inbox',
            name='items',
        ),
        migrations.AddField(
            model_name='inbox',
            name='items',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='social_distribution.inboxitem'),
            preserve_default=False,
        ),
    ]
