# Generated by Django 4.1.7 on 2023-03-27 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_distribution', '0009_remove_like_object_remove_like_summary_like_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='like',
            name='post',
        ),
        migrations.AddField(
            model_name='like',
            name='summary',
            field=models.CharField(default='No summary', max_length=200),
        ),
    ]
