# Generated by Django 4.1.7 on 2023-03-27 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_distribution', '0010_remove_like_comment_remove_like_post_like_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='object',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='like',
            name='type',
            field=models.CharField(default='Like', max_length=200),
        ),
    ]
