# Generated by Django 4.1.7 on 2023-03-27 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_distribution', '0011_like_object_alter_like_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='objectLiked',
            field=models.CharField(choices=[('Comment', 'Comment'), ('Post', 'Post'), ('None', 'None')], default='', max_length=200),
        ),
    ]
