# Generated by Django 4.1.7 on 2023-03-27 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_distribution', '0012_like_objectliked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='objectLiked',
            field=models.CharField(choices=[('Comment', 'Comment'), ('Post', 'Post'), ('None', 'None')], default='None', max_length=200),
        ),
    ]
