# Generated by Django 4.1.7 on 2023-03-07 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_distribution', '0016_alter_request_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendrequest',
            name='actor',
        ),
        migrations.RemoveField(
            model_name='friendrequest',
            name='object',
        ),
        migrations.AddField(
            model_name='author',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='followers', to='social_distribution.author'),
        ),
        migrations.DeleteModel(
            name='Followers',
        ),
        migrations.DeleteModel(
            name='friendRequest',
        ),
    ]
