# Generated by Django 4.1.7 on 2023-03-08 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_distribution', '0018_remove_author_followers_author_followering'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='followering',
            new_name='following',
        ),
    ]
