# Generated by Django 4.1.7 on 2023-03-14 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_distribution', '0022_like_comment_alter_like_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inboxitem',
            name='requests',
        ),
        migrations.AddField(
            model_name='follow',
            name='summary',
            field=models.CharField(default='No summary', max_length=200),
        ),
        migrations.AddField(
            model_name='inboxitem',
            name='follows',
            field=models.ManyToManyField(blank=True, to='social_distribution.follow'),
        ),
        migrations.DeleteModel(
            name='Request',
        ),
    ]
